### ISSUE TITLE
Documentation update: Best practice for PWA drawer

### ISSUE THREAD

**Issue by pnull** [pace/cloud-sdk-ios#1]
Add a best practice section outlining that the PAW drawer should be closed with its own close action (swipe down should be prevented!)

**Comment by EmDee** [comment]
Internal link: https://lab.jamit.de/pace/mobile/ios/pace-cloud-sdk/-/issues/215

**Comment by patrickniepel** [comment]
Done in https://github.com/pace/cloud-sdk-ios/commit/47872e3eb2569ea4c0b5329660264b495e6fcdb2

Closes #1
