### ISSUE TITLE
Missing binary for version 11.0.0

### ISSUE THREAD

**Issue by tarasChernysh** [pace/cloud-sdk-ios#3]
Could you please add binary for 11.0 version [here](https://github.com/pace/cloud-sdk-ios/releases/tag/11.0.0) ?
I see it for 12 and 10, but missing for 11.

**Comment by EmDee** [comment]
Hi @tarasChernysh, thanks for pointing that out, we indeed forgot to upload the binary. Out of interest, what do you need version 11 for? We always recommend to use the latest version, in this case version 12.

**Comment by tarasChernysh** [comment]
Thanks for suck a quick reply. 
I use Swift 5, Xcode 14.1. And if using v.12.0.0 I get error of swift version 5.7

I see this error 
<img width="847" alt="Screenshot 2022-12-01 at 10 04 10" src="https://user-images.githubusercontent.com/32072147/204998547-f53b74e6-5ca0-4e19-bb52-9f1a676cc498.png">

**Comment by EmDee** [comment]
I see, you would still get the same error when using the binary for version 11, because that one was built with Xcode 13. Any reason you are not using SPM or CocoaPods?

**Comment by EmDee** [comment]
Can you also drop me a mail at martin.dinh@pace.car please?

**Comment by tarasChernysh** [comment]
> I see, you would still get the same error when using the binary for version 11, because that one was built with Xcode 13. Any reason you are not using SPM or CocoaPods?

No reason, because I had the same error using Cocoapods. That's why try to use this way :)

**Comment by tarasChernysh** [comment]
> Can you also drop me a mail at [martin.dinh@pace.car](mailto:martin.dinh@pace.car) please?

done

**Comment by EmDee** [comment]
FYI: I deleted the comment with the email address.

**Comment by EmDee** [comment]
Version 13.0.0 is available, which was built with Xcode 14.1, please give it a try.

**Comment by tarasChernysh** [comment]
Perfect it works as expected🙂. Thank you!
