### ISSUE TITLE
Undefined symbols for architecture x86_64 BiometryPolicy.o

### ISSUE THREAD

**Issue by tarasChernysh** [pace/cloud-sdk-ios#4]
Hello, 
I often get that error when checkout git branch, change scheme.

Sometimes it can be fixed using next step like cmd+c, remove Derive data, remove Pace pod, add Pace pod, pod install. 
Sometimes it can be fixed force quit Xcode or restart MacBook.
I also checked here https://stackoverflow.com/questions/18408531/xcode-build-failure-undefined-symbols-for-architecture-x86-64 sometimes it can be helpful.
Please help me to figure it out how I can get rid of that annoying error.

<img width="439" alt="Screenshot 2023-02-03 at 12 30 02" src="https://user-images.githubusercontent.com/32072147/216578614-6dfbbf97-cb26-4342-8a31-cd00487ce52b.png">

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MF_Base32Codec", referenced from:
      objc-class-ref in BiometryPolicy.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

Xcode: 14.1
Processor: Intel 
iOS: 13
PaceSDK: 13.1.0

PodFile:

```
platform :ios,'13.0'
use_frameworks!
inhibit_all_warnings!

raise 'Please use bundle exec to run the pod command' unless defined?(Bundler)

workspace 'App.xcworkspace'

def some_pods
  pod 'BaseApp', :path => 'modules/BaseApp', :testspecs => ['Tests']
end

def public_pods
    #
end

target 'SomeTarget' do
  
    inherit! :search_paths
    project 'apps/SomeTarget/SomeTarget.xcodeproj'

    some_pods
    public_pods

    target 'Tests' do
        inherit! :search_paths
    end

end
```

Spec file: 
```
Pod::Spec.new do |s|
  s.name             = 'BaseApp'
  s.version          = '0.1.0'
  s.summary          = 'A short description of BaseApp.'
  s.description      = "BaseApp is part of the App"
  s.homepage         = 'https://www.google.com'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'aaaaa' => 'info@aaaaaa.aa' }
  s.source           = { :git => 'https://sorce', :tag => s.version.to_s }

  s.ios.deployment_target = '13.0'

  s.source_files = 'BaseApp/Classes/**/*'
#  s.resource = 'BaseApp/Assets/**/*.strings'

  #  framework
  s.dependency 'SomeResources'
  s.dependency 'SomeSDK'
  s.dependency 'SomeUtils'

  # Public
  s.dependency 'PACECloudSDK', '~> 13.1.0'
  s.static_framework = true

  s.test_spec 'Tests' do |test_spec|
    test_spec.source_files = 'BaseApp/Tests/**/*.swift'
  end
end
```

**Comment by EmDee** [comment]
@tarasChernysh Thanks for reporting, but this is unfortunately an Xcode/CocoaPods issue where we cannot do much about.

We will check, if we can get rid of the external dependency in one of our next versions, but until then you unfortunately have to use your mentioned workarounds.

I can recommend SPM, which doesn't have the issue.

**Comment by tarasChernysh** [comment]
@EmDee hello, 
I also tried to add manually pacesdk, but have the same issue. 

With SPM I haven't found any solution how I can use it, because we have the following project structure: 

-MainAppTarget
-Pods
---DevPods
-----BaseApp
-----SomeSDK

So when I added pacesdk to `Pods` target each time I execute command `pod install` SPM is cleaned up. 
Do you know how to solve it?

**Comment by patrickniepel** [comment]
Hi @tarasChernysh 

Looking at your project structure, the Swift package of our SDK probably needs to be added to the `MainAppTarget` target instead of the `Pods` target

**Comment by tarasChernysh** [comment]
thanks. We can't change project structure.
Do you know why we have the same issue if we use manually integration?

**Comment by tarasChernysh** [comment]
because my workarounds don't help me anymore

**Comment by patrickniepel** [comment]
> We can't change project structure.

You don't have to change the project structure in order for SPM to work. 
I assume the `MainAppTarget` is the one needing the SDK? In that case, all you have to do is to follow the instructions in here: https://docs.pace.cloud/integrating/mobile-app/ios

**Comment by tarasChernysh** [comment]
@patrickniepel  I need to use `PaceSDK` only in `BaseApp`. Not in `MainAppTarget`

**Comment by EmDee** [comment]
@tarasChernysh We've removed the dependency to Base32 altogether in the latest release (`14.0.0`). Please test again. I'll close this for now.

**Comment by tarasChernysh** [comment]
thanks, 
it works🙂
