### ISSUE TITLE
Custom identity provider without IDKit doesn't work

### ISSUE THREAD

**Issue by tarasChernysh** [pace/cloud-sdk-ios#5]
I try to use a custom identity provider without IDKit from this [doc](https://docs.pace.cloud/integrating/mobile-app/custom-identity-provider), but it doesn't call the any delegate's methods. 
What was the reason for that? 
What is  the proper way to handle any error in `func getAccessToken(...)`? Because there is only handling access token response.

```
protocol PaceSDKHelperProtocol {    
    func setup(_ secret: PaceSDKSecret)
}

final class PaceSDKHelper: PaceSDKHelperProtocol {
    
    private let appKitDelegate = PaceAppKitDelegate()
    
    func setup(_ secret: PaceSDKSecret) {
        
        let environment = PACECloudSDK.Environment(rawValue: secret.environment) ?? .sandbox
        let configuration: PACECloudSDK.Configuration = .init(
            apiKey: secret.apiKey,
            authenticationMode: .native,
            environment: environment,
            customOIDConfiguration: nil,
            isRedirectSchemeCheckEnabled: false
        )
        
        PACECloudSDK.shared.setup(with: configuration)

	// second time to set delegate here after PACE SDK configuration
        AppKit.delegate = self.appKitDelegate
    }
}

final class PaceAppKitDelegate: AppKitDelegate {
    
    init() {
        AppKit.delegate = self
    }
    
    deinit {
	// it doesn’t call, so it's alive
        print("👻 deinit PaceAppKitDelegate")
    }
    
    func getAccessToken(
        reason: AppKit.GetAccessTokenReason,
        oldToken: String?,
        completion: @escaping ((API.Communication.GetAccessTokenResponse) -> Void)
    ) {

        self.getPaceToken { result in
            switch result {
            case let .success(token):
                let response = API.Communication.GetAccessTokenResponse(accessToken: token, isInitialToken: nil)
                completion(response)

            case let .failure(failure):
		// it’s not calling 		// how to handle this error?
                LOG.d("error get pace token \(failure)")
            }
        }
    }

    func didFail(with error: AppKit.AppError) {
        LOG.d("error get pace token \(error)")
    }
    
    // MARK: - Private
    
    private func getPaceToken(completion: @escaping (Result<String, Error>) -> Void) {
        // some logic to get pace access token
     }
}

```

Xcode 14.2
iOS 16.2 (simulator), 16.6.1 (device)
PACE SDK 14.0.0 (for simulator), 13.0.1 (for device)

**Comment by patrickniepel** [comment]
Hi @tarasChernysh 

> but it doesn't call any delegate's methods

Can you tell me a bit more about your current use case? Are you expecting the `getAccessToken` delegate method to be called right at app launch / SDK setup? If that's the case, it's not how `AppKit` works. The purpose of `AppKit` is to help you manage PACE's web apps that you may present via `AppKit.appViewController(String)`. You can find examples [here](https://docs.pace.cloud/integrating/mobile-app/show-predefined-apps) and [here](https://docs.pace.cloud/integrating/mobile-app/initiate-the-fueling-process). Only when presenting those view controllers, the `getAccessToken` delegate method will be triggered.

> What is the proper way to handle any error in func getAccessToken(...)?

In this case, simply pass `""` as the `accessToken` via `API.Communication.GetAccessTokenResponse`. The SDK will handle it appropriately.

**Comment by tarasChernysh** [comment]
@patrickniepel  Yes, I want to display `AppKit.appViewController(String)`, and before calling that I configured PACE SDK. It's displayed, but with an error page (it's a screen with prompt to login), because delegate methods weren't triggered.

**Comment by patrickniepel** [comment]
Is it possible that your `Info.plist` still contains the `PACECloudSDKIDKitSetup` key?

**Comment by tarasChernysh** [comment]
Yes, it's still there.

**Comment by tarasChernysh** [comment]
I removed that object - endless spinner in v14.0.0. I am going to check in v13.0.1 as well

**Comment by patrickniepel** [comment]
I just pasted your code into a new project and I unfortunately can't reproduce the error. The `getAccessToken` method gets called as soon as I present the app view controller.

**Comment by tarasChernysh** [comment]
Did you configure PACE SDK right before presenting  `AppKit.appViewController(String)`? 
PACE SDK v14.0.0? Simulator?

**Comment by patrickniepel** [comment]
The SDK has to be configured before anything else, preferably right at app start.
I was using the latest SDK version though but there were no relevant changes in between. Anyway, I will ask the team for further investigation.

**Comment by tarasChernysh** [comment]
I don't need to configure PACE SDK when the app is launched. From PACE SDK I use only `AppKit.appViewController(String)` that's why I had done that configuration right before presenting AppKit controller. I will be back on Monday and will continue working on that part. Thanks for your help.

**Comment by tarasChernysh** [comment]
@patrickniepel hello, 
yes, it works now. Could you please update your documentation with a mention of removing key from Info.plist file?

**Comment by patrickniepel** [comment]
Will do 👍
